// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvpnLSkuHaWZrThv_T0B0xV6ZS_67q7Wo',
    appId: '1:937309528352:web:706995dc00c476d8897745',
    messagingSenderId: '937309528352',
    projectId: 'my-application-b8587',
    authDomain: 'my-application-b8587.firebaseapp.com',
    storageBucket: 'my-application-b8587.appspot.com',
    measurementId: 'G-068GVVCW6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbDixjNJ3pEMtS5NudCxJpgl6N7Txbwb8',
    appId: '1:937309528352:android:0dce620eb665a6a6897745',
    messagingSenderId: '937309528352',
    projectId: 'my-application-b8587',
    storageBucket: 'my-application-b8587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGR7Hl0VOZShk2YPJHDQ-wV8Akf41RLNs',
    appId: '1:937309528352:ios:44ad89a630016016897745',
    messagingSenderId: '937309528352',
    projectId: 'my-application-b8587',
    storageBucket: 'my-application-b8587.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGR7Hl0VOZShk2YPJHDQ-wV8Akf41RLNs',
    appId: '1:937309528352:ios:a6b9648c19ccf851897745',
    messagingSenderId: '937309528352',
    projectId: 'my-application-b8587',
    storageBucket: 'my-application-b8587.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
